//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebsite_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        public Blogs()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public short BlogId { get; set; }
        public Nullable<short> UserId { get; set; }
        public Nullable<short> CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<short> ImageId { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Images Images { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
