//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebsite_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public Images()
        {
            this.Blogs = new HashSet<Blogs>();
            this.UserDetails = new HashSet<UserDetails>();
        }
    
        public short ImageId { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ICollection<Blogs> Blogs { get; set; }
        public virtual ICollection<UserDetails> UserDetails { get; set; }
    }
}
